### ISSUE TITLE
Error on new project with MAUI Embedding turn on

### ISSUE THREAD

**Issue by jeromelaban** [unoplatform/uno.extensions#2223]
### Discussed in https://github.com/unoplatform/uno/discussions/15837

<div type='discussions-op-text'>

<sup>Originally posted by **WenHong-Lau** March 10, 2024</sup>
These are the options selected in the wizard
![image](https://github.com/unoplatform/uno/assets/88780667/a6fec59a-f93c-41fd-ba7f-d4810c1ae9c0)

These are the errors I've encountered.
![image](https://github.com/unoplatform/uno/assets/88780667/81b50c72-6605-448f-9b1e-c1539c02b188)
</div>

**Comment by agneszitte** [comment]
@jeromelaban, @dansiegel, @Youssef1313 (cc @Darsh0307)
I just did a new test with the same options with the latest vsix (uno.platform-5.2.0-dev.**108**.vsix):
All platforms:
```
error NU1605: Warning As Error: Detected package downgrade: Xamarin.AndroidX.Collection from 1.4.0.1 to 1.3.0.1. Reference the package directly from the project to select a different version. 
error NU1605:  TestNewProjectMauiEmbeddingVsixVersion108 -> Xamarin.AndroidX.Activity 1.8.2.1 -> Xamarin.AndroidX.Collection (>= 1.4.0.1) 
error NU1605:  TestNewProjectMauiEmbeddingVsixVersion108 -> Xamarin.AndroidX.Collection (>= 1.3.0.1)
```

I think it is related to this recent change in the Uno repo, right?
https://github.com/unoplatform/uno/blame/7acdc5dcfe9065a0868c436c0ec867c45e012728/src/Uno.Sdk/Tasks/ImplicitPackagesResolver.cs#L201

**Comment by agneszitte** [comment]
@dansiegel After updating locally to 1.4.0.1 in packages.json for `Xamarin.AndroidX.Collection` to see if there are other errors, I am not getting this error:
```
error NU1201: Project TestNewProject is not compatible with net8.0 (.NETCoreApp,Version=v8.0). Project TestNewProject.MauiControls supports:
1>C:\Dev\Samples\TestNewProject\TestNewProject\TestNewProject.csproj : error NU1201:   - net8.0-android34.0 (.NETCoreApp,Version=v8.0)
1>C:\Dev\Samples\TestNewProjec\TestNewProject\TestNewProject.csproj : error NU1201:   - net8.0-ios17.2 (.NETCoreApp,Version=v8.0)
1>C:\Dev\Samples\TestNewProject\TestNewProject\TestNewProject.csproj : error NU1201:   - net8.0-maccatalyst17.2 (.NETCoreApp,Version=v8.0)
1>C:\Dev\Samples\TestNewProject\TestNewProject\TestNewProject.csproj : error NU1201:   - net8.0-windows10.0.19041 (.NETCoreApp,Version=v8.0)
```

**Comment by agneszitte** [comment]
@dansiegel, @jeromelaban now here are the errors I am getting with the same options with the prod **stable vsix version 5.1.22.24** this time.
All platforms:
```
2>C:\Program Files\dotnet\packs\Microsoft.Android.Sdk.Windows\34.0.79\tools\Xamarin.Android.Aapt2.targets(156,3): error APT2260: resource style/Theme.MaterialComponents.DayNight (aka TestNewProjectMauiEmbeddingStableVsix.TestNewProjectMauiEmbeddingStableVsix:style/Theme.MaterialComponents.DayNight) not found.
2>C:\Program Files\dotnet\packs\Microsoft.Android.Sdk.Windows\34.0.79\tools\Xamarin.Android.Aapt2.targets(156,3): error APT2260:
2>C:\Dev\Samples\TestNewProjectMauiEmbeddingStableVsix\TestNewProjectMauiEmbeddingStableVsix\obj\Debug\net8.0-android\lp\161\jl\res\values\styles.xml(5): error APT2260: resource attr/colorOnSurface (aka TestNewProjectMauiEmbeddingStableVsix.TestNewProjectMauiEmbeddingStableVsix:attr/colorOnSurface) not found.
2>C:\Dev\Samples\TestNewProjectMauiEmbeddingStableVsix\TestNewProjectMauiEmbeddingStableVsix\obj\Debug\net8.0-android\lp\161\jl\res\values\styles.xml(5): error APT2260:
2>C:\Program Files\dotnet\packs\Microsoft.Android.Sdk.Windows\34.0.79\tools\Xamarin.Android.Aapt2.targets(156,3): error APT2260: resource style/ThemeOverlay.MaterialComponents.MaterialAlertDialog (aka TestNewProjectMauiEmbeddingStableVsix.TestNewProjectMauiEmbeddingStableVsix:style/ThemeOverlay.MaterialComponents.MaterialAlertDialog) not found.
2>C:\Program Files\dotnet\packs\Microsoft.Android.Sdk.Windows\34.0.79\tools\Xamarin.Android.Aapt2.targets(156,3): error APT2260:
2>C:\Dev\Samples\TestNewProjectMauiEmbeddingStableVsix\TestNewProjectMauiEmbeddingStableVsix\obj\Debug\net8.0-android\lp\161\jl\res\values\styles.xml(5): error APT2260: resource attr/colorOnSurface (aka TestNewProjectMauiEmbeddingStableVsix.TestNewProjectMauiEmbeddingStableVsix:attr/colorOnSurface) not found.
2>C:\Dev\Samples\TestNewProjectMauiEmbeddingStableVsix\TestNewProjectMauiEmbeddingStableVsix\obj\Debug\net8.0-android\lp\161\jl\res\values\styles.xml(5): error APT2260:
2>C:\Program Files\dotnet\packs\Microsoft.Android.Sdk.Windows\34.0.79\tools\Xamarin.Android.Aapt2.targets(156,3): error APT2260: resource style/Widget.Material3.CompoundButton.CheckBox (aka TestNewProjectMauiEmbeddingStableVsix.TestNewProjectMauiEmbeddingStableVsix:style/Widget.Material3.CompoundButton.CheckBox) not found.
2>C:\Program Files\dotnet\packs\Microsoft.Android.Sdk.Windows\34.0.79\tools\Xamarin.Android.Aapt2.targets(156,3): error APT2260:
2>C:\Program Files\dotnet\packs\Microsoft.Android.Sdk.Windows\34.0.79\tools\Xamarin.Android.Aapt2.targets(156,3): error APT2062: failed linking references.
2>C:\Program Files\dotnet\packs\Microsoft.Android.Sdk.Windows\34.0.79\tools\Xamarin.Android.Aapt2.targets(156,3): error APT2062:
2>Done building project "TestNewProjectMauiEmbeddingStableVsix.csproj" -- FAILED.
```

**Comment by jeromelaban** [comment]
5.1.27 is being published to nuget.

**Comment by nickrandolph** [comment]
@agneszitte it looks like we need a different version variable for Xamarin.AndroidX.Collection.Ktx as it doesn't seem to be versioned the same as Xamarin.AndroidX.Collection (@dansiegel you might need to fix this in template).
@agneszitte for Windows, can you try pushing to latest release of WinAppSdk and BuildTools and see if that fixes the build error

**Comment by agneszitte** [comment]
> @agneszitte it looks like we need a different version variable for Xamarin.AndroidX.Collection.Ktx as it doesn't seem to be versioned the same as Xamarin.AndroidX.Collection (@dansiegel you might need to fix this in template). @agneszitte for Windows, can you try pushing to latest release of WinAppSdk and BuildTools and see if that fixes the build error

Yes let me give it a try

**Comment by dansiegel** [comment]
@agneszitte please retest with the latest from the Template (see PR unoplatform/uno.templates#608). Also I'm not able to play the video you uploaded. And you do indeed need the latest version of WinAppSdk.

**Comment by agneszitte** [comment]
> @agneszitte please retest with the latest from the Template (see PR [unoplatform/uno.templates#608](https://github.com/unoplatform/uno.templates/pull/608)). Also, I'm not able to play the video you uploaded. And you do indeed need the latest version of WinAppSdk.

@dansiegel I tested with latest template [5.3.0-dev.19](https://dev.azure.com/uno-platform/Uno%20Platform/_build/results?buildId=120036&view=results) + latest dev packages (I did not make any updates or changes whatsoever).
*Still matching the same options mentioned in the issue:
```
dotnet new unoapp -o TestCustomApp530dev19 -preset "recommended" -platforms "android" -platforms "ios" -platforms "maccatalyst" -platforms "windows" -auth "oidc" -theme-service  -pwa False -maui  -theme "material" -presentation "mvvm" -config  -di  -log "serilog" -nav "regions" -http  -loc  -tests "unit" -tests "ui" -toolkit  -dsp  -id "com.companyname.TestCustomApp530dev19" -pub "O=TestCustomApp530dev19"
```
Versions used (by default when creating the app) for my tests:
```
    <UnoExtensionsVersion>4.2.0-dev.13</UnoExtensionsVersion>
    <UnoToolkitVersion>5.2.0-dev.56</UnoToolkitVersion>
    <UnoThemesVersion>4.2.0-dev.30</UnoThemesVersion>
    <UnoCSharpMarkupVersion>5.3.0-dev.11</UnoCSharpMarkupVersion>
    Microsoft.WindowsAppSDK: 1.5.240311000
    Microsoft.Windows.SDK.BuildTools: 10.0.22621.3233
    MauiVersion: 8.0.6
```
Sample app created: [TestCustomApp530dev19.zip](https://github.com/unoplatform/uno.extensions/files/14923578/TestCustomApp530dev19.zip)

---
## Results
- ❌ Windows: 
  Building fine but still getting the same exception I shared previously [here](https://github.com/unoplatform/uno.extensions/issues/2223#issuecomment-2043759370) when launching the app
- ✔️ Android: 
  Building and launching fine
- ❌ iOS: 
	Building fine but this exception when launching the app
   `$exception.Message.Message: Uno.Extensions.Maui.MauiEmbeddingException: 'CoreWindow is missing _window internal field required to access UIWindow, you may need an updated version of the Uno.Extension.Maui.WinUI package.'`
   But it is already using the latest dev version **Uno.Extension.Maui.WinUI 4.2.0-dev.13**
   ```
   $exception.InnerException: null
   ```
   ```
   $exception.StackTrace.StackTrace:
      at Uno.Extensions.Maui.MauiEmbedding.<>c.<RegisterPlatformServices>b__0_0(IServiceProvider sp)
   at Microsoft.Extensions.DependencyInjection.ServiceLookup.CallSiteRuntimeResolver.VisitFactory(FactoryCallSite factoryCallSite, RuntimeResolverContext context)
   at Microsoft.Extensions.DependencyInjection.ServiceLookup.CallSiteVisitor`2[[Microsoft.Extensions.DependencyInjection.ServiceLookup.RuntimeResolverContext, Microsoft.Extensions.DependencyInjection, Version=8.0.0.0, Culture=neutral, PublicKeyToken=adb9793829ddae60],[System.Object, System.Private.CoreLib, Version=8.0.0.0, Culture=neutral, PublicKeyToken=7cec85d7bea7798e]].VisitCallSiteMain(ServiceCallSite callSite, RuntimeResolverContext argument)
   at Microsoft.Extensions.DependencyInjection.ServiceLookup.CallSiteRuntimeResolver.VisitRootCache(ServiceCallSite callSite, RuntimeResolverContext context)
   at Microsoft.Extensions.DependencyInjection.ServiceLookup.CallSiteVisitor`2[[Microsoft.Extensions.DependencyInjection.ServiceLookup.RuntimeResolverContext, Microsoft.Extensions.DependencyInjection, Version=8.0.0.0, Culture=neutral, PublicKeyToken=adb9793829ddae60],[System.Object, System.Private.CoreLib, Version=8.0.0.0, Culture=neutral, PublicKeyToken=7cec85d7bea7798e]].VisitCallSite(ServiceCallSite callSite, RuntimeResolverContext argument)
   at Microsoft.Extensions.DependencyInjection.ServiceLookup.CallSiteRuntimeResolver.Resolve(ServiceCallSite callSite, ServiceProviderEngineScope scope)
   at Microsoft.Extensions.DependencyInjection.ServiceProvider.CreateServiceAccessor(ServiceIdentifier serviceIdentifier)
   at System.Collections.Concurrent.ConcurrentDictionary`2[[Microsoft.Extensions.DependencyInjection.ServiceLookup.ServiceIdentifier, Microsoft.Extensions.DependencyInjection, Version=8.0.0.0, Culture=neutral, PublicKeyToken=adb9793829ddae60],[Microsoft.Extensions.DependencyInjection.ServiceProvider.ServiceAccessor, Microsoft.Extensions.DependencyInjection, Version=8.0.0.0, Culture=neutral, PublicKeyToken=adb9793829ddae60]].GetOrAdd(ServiceIdentifier key, Func`2 valueFactory)
   at Microsoft.Extensions.DependencyInjection.ServiceProvider.GetService(ServiceIdentifier serviceIdentifier, ServiceProviderEngineScope serviceProviderEngineScope)
   at Microsoft.Extensions.DependencyInjection.ServiceProvider.GetService(Type serviceType)
   at Microsoft.Maui.MauiContext.WrappedServiceProvider.GetService(Type serviceType)
   at Microsoft.Extensions.DependencyInjection.ServiceProviderServiceExtensions.GetRequiredService(IServiceProvider provider, Type serviceType)
   at Microsoft.Extensions.DependencyInjection.ServiceProviderServiceExtensions.GetRequiredService[UIWindow](IServiceProvider provider)
   at Uno.Extensions.Maui.MauiEmbedding.InitializeApplicationMainPage(IApplication iApp)
   at Uno.Extensions.Maui.MauiEmbedding.InitializeMauiEmbeddingApp(MauiApp mauiApp, Application app)
   at Uno.Extensions.Maui.MauiEmbedding.BuildMauiApp(MauiAppBuilder builder, Application app, Window window)
   at Uno.Extensions.Maui.MauiEmbedding.<>c__DisplayClass3_0`1[[TestCustomApp530dev19.MauiControls.App, TestCustomApp530dev19.MauiControls, Version=1.0.0.0, Culture=neutral, PublicKeyToken=null]].<UseMauiEmbedding>b__0()
   at Uno.Extensions.Maui.UnoServiceProviderFactory.CreateBuilder(IServiceCollection services)
   at Uno.Extensions.Hosting.Internal.ServiceFactoryAdapter`1[[System.IServiceProvider, System.ComponentModel, Version=8.0.0.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a]].CreateBuilder(IServiceCollection services)
   at Uno.Extensions.Hosting.HostBuilder.CreateServiceProvider()
   at Uno.Extensions.Hosting.HostBuilder.Build()
   at Uno.Extensions.Hosting.ApplicationBuilder.Build()
   at Uno.Extensions.ApplicationBuilderExtensions.<>c__DisplayClass0_0`1[[TestCustomApp530dev19.Presentation.Shell, TestCustomApp530dev19, Version=1.0.0.0, Culture=neutral, PublicKeyToken=null]].<NavigateAsync>b__1()
   at Uno.Extensions.ServiceProviderExtensions.BuildAndInitializeHostAsync(Window window, FrameworkElement viewHost, Func`1 buildHost, String initialRoute, Type initialView, Type initialViewModel, Func`3 initialNavigate)
   at Uno.Extensions.ApplicationBuilderExtensions.<NavigateAsync>d__0`1[[TestCustomApp530dev19.Presentation.Shell, TestCustomApp530dev19, Version=1.0.0.0, Culture=neutral, PublicKeyToken=null]].MoveNext()
   at TestCustomApp530dev19.App.OnLaunched(LaunchActivatedEventArgs args) in C:\Dev\Samples\[Uno] My Own - custom\Cli\TestCustomApp530dev19\TestCustomApp530dev19\App.xaml.cs:line 100
   at System.Threading.Tasks.Task.<>c.<ThrowAsync>b__128_0(Object state)
   at Foundation.NSAsyncSynchronizationContextDispatcher.Apply() in /Users/builder/azdo/_work/1/s/xamarin-macios/src/Foundation/NSAction.cs:line 176
   at UIKit.UIApplication.UIApplicationMain(Int32 argc, String[] argv, IntPtr principalClassName, IntPtr delegateClassName) in /Users/builder/azdo/_work/1/s/xamarin-macios/src/UIKit/UIApplication.cs:line 58
   at UIKit.UIApplication.Main(String[] args, Type principalClass, Type delegateClass) in /Users/builder/azdo/_work/1/s/xamarin-macios/src/UIKit/UIApplication.cs:line 94
   at TestCustomApp530dev19.iOS.EntryPoint.Main(String[] args) in C:\Dev\Samples\[Uno] My Own - custom\Cli\TestCustomApp530dev19\TestCustomApp530dev19\Platforms\iOS\Main.iOS.cs:line 12
   ```
	```
	   Call Stack:
	    0x11 in System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw	C#
	 	0x6 in System.Threading.Tasks.Task.<>c.<ThrowAsync>b__128_0	C#
	 	0xC in Foundation.NSAsyncSynchronizationContextDispatcher.Apply at /Users/builder/azdo/_work/1/s/xamarin-macios/src/Foundation/NSAction.cs:176,5	C#
	 	0x38 in UIKit.UIApplication.xamarin_UIApplicationMain	C#
	 	0xE in UIKit.UIApplication.UIApplicationMain at /Users/builder/azdo/_work/1/s/xamarin-macios/src/UIKit/UIApplication.cs:58,4	C#
	 	0x51 in UIKit.UIApplication.Main at /Users/builder/azdo/_work/1/s/xamarin-macios/src/UIKit/UIApplication.cs:94,4	C#
	>	0xD in TestCustomApp530dev19.iOS.EntryPoint.Main at C:\Dev\Samples\[Uno] My Own - custom\Cli\TestCustomApp530dev19\TestCustomApp530dev19\Platforms\iOS\Main.iOS.cs:12,9	C#
	```

**Comment by agneszitte** [comment]
Based on the latest test [here](https://github.com/unoplatform/uno.extensions/issues/2223#issuecomment-2046002801), I am now closing this issue as there are **no more building errors for all platforms with the latest template and versions.**
___
_The exceptions when launching the app for Windows and iOS will be tracked with: https://github.com/unoplatform/uno.extensions/issues/2241 and https://github.com/unoplatform/uno.extensions/issues/2240_.
