### ISSUE TITLE
[Navigation] In wasm doesnt work  _navigator.ShowMessageDialogAsync

### ISSUE THREAD

**Issue by brunodamaso** [unoplatform/uno.extensions#2275]
## Current behavior

in wasm doesnt work  _navigator.ShowMessageDialogAsync, 

## Expected behavior
Open a dialog message 

## How to reproduce it (as minimally and precisely as possible)
create an aplication with uno template wizard v.5.2.46 (latest) with the following characteristics
![image](https://github.com/unoplatform/uno.extensions/assets/63899828/4f3f70cd-8b44-49f8-b608-e5726024f14b)

in MainViewModel.cs change this:
 private async Task GoToSecondView()
 {
     await _navigator.ShowMessageDialogAsync<object>(this, title: "titulo", content: "content");
     //await _navigator.NavigateViewModelAsync<SecondViewModel>(this, data: new Entity(Name!));
 }
compile and run in winAppSDK and OK, compile and run in webassembly doesnt show dialog message, and the button keep blocked

## Environment

Nuget Package (s):
   <UnoFeatures>
 CSharpMarkup;
 Hosting;
 Toolkit;
 Mvvm;
 Navigation;
   </UnoFeatures>

Package Version(s):
"Uno.Sdk": "5.2.108"

Affected platform(s):

- [ ] iOS
- [ ] macOS (AppKit)
- [ ] Mac Catalyst
- [ ] Android
- [X] WebAssembly
- [ ] Windows
- [ ] Skia (WPF)
- [ ] Skia (GTK on Linux/macOS/Windows)
- [ ] Skia (Linux Framebuffer)
- [ ] Build tasks

Visual Studio:

- [ ] 2019 (version: )
- [X] 2022 (version: ) 17.9.6
- [ ] Visual Studio Code (version: )
- [ ] Rider Windows (version: )
- [ ] Rider macOS (version: )

Relevant plugins:
none
- [ ] Resharper (version: )

**Comment by nickrandolph** [comment]
@brunodamaso thanks for reporting this. We'll investigate this and reply when we know more

**Comment by HakanL** [comment]
I have the same issue in Skia, the button gets disabled and no Message Dialog is shown. Here's a repo: https://github.com/HakanL/Uno.MessageDlg

In my full solution I catch this exception when I'm trying to display the message dialog. I'm not 100% sure it's related as I don't see it in the above repo, but it may be that there isn't a handler for it (unhandled tasks):
```
Unhandled Task exception: One or more errors occurred. (Trying to set position of the dialog before it is associated with a visual tree. Make sure to use InitializeWithWindow before calling ShowAsync.)
System.AggregateException: One or more errors occurred. (Trying to set position of the dialog before it is associated with a visual tree. Make sure to use InitializeWithWindow before calling ShowAsync.)
 ---> System.InvalidOperationException: Trying to set position of the dialog before it is associated with a visual tree. Make sure to use InitializeWithWindow before calling ShowAsync.
   at Microsoft.UI.Xaml.Controls.ContentDialog.SizeAndPositionContentInPopup() in /__w/1/s/src/Uno.UI/UI/Xaml/Controls/ContentDialog/ContentDialog.Visuals.cs:line 220
   at Microsoft.UI.Xaml.Controls.ContentDialog.PrepareContent() in /__w/1/s/src/Uno.UI/UI/Xaml/Controls/ContentDialog/ContentDialog.Visuals.cs:line 192
   at Microsoft.UI.Xaml.Controls.ContentDialog.OnApplyTemplate() in /__w/1/s/src/Uno.UI/UI/Xaml/Controls/ContentDialog/ContentDialog.cs:line 243
   at Microsoft.UI.Xaml.Controls.Control.TryCallOnApplyTemplate() in /__w/1/s/src/Uno.UI/UI/Xaml/Controls/Control/Control.cs:line 320
   at Microsoft.UI.Xaml.Controls.Control.ApplyTemplate() in /__w/1/s/src/Uno.UI/UI/Xaml/Controls/Control/Control.cs:line 484
   at Microsoft.UI.Xaml.Controls.Control.EnsureTemplate() in /__w/1/s/src/Uno.UI/UI/Xaml/Controls/Control/Control.cs:line 495
   at Microsoft.UI.Xaml.Controls.ContentDialog.<ShowAsync>b__32_0(CancellationToken ct) in /__w/1/s/src/Uno.UI/UI/Xaml/Controls/ContentDialog/ContentDialog.cs:line 312
   at Windows.Foundation.AsyncOperation`1.BuildTaskAsync(FuncAsync`2 taskBuilder) in /__w/1/s/src/Uno.Foundation/Internal/AsyncOperation.TResult.cs:line 70
   at System.WindowsRuntimeSystemExtensions.AsTaskCore[TResult](IAsyncOperation`1 source, CancellationToken ct) in /__w/1/s/src/Uno.UWP/System.Runtime/WindowsRuntimeSystemExtensions.cs:line 66
   at Uno.UI.WinRT.Extensions.UI.Popups.MessageDialogContentDialog.ShowAsync(CancellationToken ct) in /__w/1/s/src/Uno.UI/WinRT/Extensions/UI/Popups/MessageDialogContentDialog.cs:line 69
   at Uno.UI.WinRT.Extensions.UI.Popups.MessageDialogExtension.ShowAsync(CancellationToken ct) in /__w/1/s/src/Uno.UI/WinRT/Extensions/UI/Popups/MessageDialogExtension.cs:line 30
   at Windows.UI.Popups.MessageDialog.ShowInnerAsync(CancellationToken ct) in /__w/1/s/src/Uno.UWP/UI/Popups/MessageDialog.cs:line 123
   at Windows.UI.Popups.MessageDialog.<ShowAsync>b__6_0(CancellationToken ct) in /__w/1/s/src/Uno.UWP/UI/Popups/MessageDialog.cs:line 60
   at Windows.Foundation.AsyncOperation`1.BuildTaskAsync(FuncAsync`2 taskBuilder) in /__w/1/s/src/Uno.Foundation/Internal/AsyncOperation.TResult.cs:line 70
   at System.WindowsRuntimeSystemExtensions.AsTaskCore[TResult](IAsyncOperation`1 source, CancellationToken ct) in /__w/1/s/src/Uno.UWP/System.Runtime/WindowsRuntimeSystemExtensions.cs:line 66
   --- End of inner exception stack trace ---
   at System.Threading.Tasks.Task.ThrowIfExceptional(Boolean includeTaskCanceledExceptions)
   at System.Threading.Tasks.Task`1.GetResultCore(Boolean waitCompletionNotification)
   at Uno.Extensions.Navigation.Navigators.MessageDialogNavigator.<>c__DisplayClass3_0.<DisplayDialog>b__1(Task`1 result)
   at System.Threading.ExecutionContext.RunInternal(ExecutionContext executionContext, ContextCallback callback, Object state)
--- End of stack trace from previous location ---
   at System.Threading.ExecutionContext.RunInternal(ExecutionContext executionContext, ContextCallback callback, Object state)
   at System.Threading.Tasks.Task.ExecuteWithThreadLocal(Task& currentTaskSlot, Thread threadPoolThread)
```

**Comment by HakanL** [comment]
Also found this in the documentation, that `InitializeWithWindow` has to be called, but I'm not sure how to call this since I'm just using the INavigator interface: https://platform.uno/docs/articles/features/dialogs.html

**Comment by HakanL** [comment]
It seems we're calling `InitializeWithWindow`, but only for WinUI: https://github.com/unoplatform/uno.extensions/blob/b9087d7c13dd694c815b05911acd391f753b902f/src/Uno.Extensions.Navigation.UI/Navigators/MessageDialogNavigator.cs#L101

Sorry for all the comments, but I just noticed the issue with the message dialogs. I had already upgraded to Uno 5.2, of course I can downgrade, but hoping for a quick fix instead.
