### ISSUE TITLE
[New Project - Custom Options] Application Fails to Launch Correctly or Displays a Blank Screen on Some Platforms with Specific Options

### ISSUE THREAD

**Issue by agneszitte** [unoplatform/uno.extensions#2418]
### Current behavior

When creating a new Uno project with certain custom options detailed below, the application does not launch correctly or displays a blank screen on some platforms.

#### Summary of the options

![image](https://github.com/unoplatform/uno.extensions/assets/16295702/5e01e69d-bcce-4c65-8308-47f48dbfd398)

<details>
<summary>Written summary of the options (click here to expand)</summary>

**Framework**
- .NET 8.0

**Platforms**
- Android, iOS, WebAssembly, macOS (Catalyst), Windows, Desktop

**Presentation**
- MVVM

**Markup**
- XAML

**Theme**
- Material, Theme Service, Import Uno DSP

**Extensions**
- Dependency Injection, Configuration, Localization, Regions, Default

**Features**
- WASM Multi-Threading, PWA Manifest, Visual Studio Code Debugging

**Authentication**
- None

**CI Pipeline**
- None

</details>

#### Related dotnet new command to create a project with these options
`dotnet new unoapp -o UnoTestNavIssue -preset "recommended" -theme-service  -wasm-multi-threading  -theme "material" -presentation "mvvm" -config  -di  -log "default" -nav "regions" -http False -loc  -tests "none" -toolkit False -dsp  -id "com.companyname.UnoTestNavIssue" -pub "O=UnoPlatform"`

### Expected behavior

The application should launch and function correctly on all specified platforms with the given custom options.

### How to reproduce it (as minimally and precisely as possible)

1. Create a new Uno project using the custom options mentioned in the issue.
2. Launch the application on all platforms.
3. Observe that on some platforms, the application does not launch correctly or displays a blank screen on some platforms.

### Workaround

N/A

### Works on UWP/WinUI

Yes

### Relevant plugins

N/A

____

### Tested with Uno.Sdk 5.2 Stable
- Microsoft Visual Studio Professional 2022 (64-bit) - Current Version 17.10.1
- Uno Extensions version: 5.2.56.70
- Uno.Sdk: 5.2.175"
- UnoExtensionsVersion: 4.1.24
- UnoToolkitVersion: 6.0.24
- UnoThemesVersion: 5.0.13
- UnoCSharpMarkupVersion: 5.2.14

	#### Results:
	- ✅**Windows**: OK
	- ✅**Android**: OK
	- ❌**WASM**: Blank page
	- ❌**iOS**: Black screen
	- ❌**Desktop**: Console is launching but not the application
	- ❌**Desktop WSL 2**: 
	```
	Exception thrown: 'System.InvalidOperationException' in System.Console.dll
	Loaded '/mnt/c/Dev/Samples/UnoTestNavIssue/UnoTestNavIssue/bin/Debug/net8.0-desktop/Uno.UI.Dispatching.dll'. Symbols loaded.
	An unhandled exception of type 'System.InvalidOperationException' occurred in System.Console.dll: 'Cannot read keys when either application does not have a console or when console input has been redirected. Try Console.Read.'
	Stack trace:
	 >   at System.ConsolePal.ReadKey(Boolean intercept)
	 >   at Uno.UI.Runtime.Skia.Linux.FrameBuffer.FrameBufferHost.<StartConsoleInterception>b__15_0()
	The thread '.NET TP Worker' (2298) has exited with code 0 (0x0).
	The thread '.NET TP Worker' (2310) has exited with code 0 (0x0).
	The thread '.NET TP Worker' (2300) has exited with code 0 (0x0).
	The thread '.NET TP Worker' (2309) has exited with code 0 (0x0).
	Loaded '/mnt/c/Dev/Samples/UnoTestNavIssue/UnoTestNavIssue/bin/Debug/net8.0-desktop/Uno.Diagnostics.Eventing.dll'. Symbol loading disabled by Include/Exclude setting.
	Loaded '/usr/lib/dotnet/shared/Microsoft.NETCore.App/8.0.7/System.Diagnostics.StackTrace.dll'. Symbol loading disabled by Include/Exclude setting.
	Unhandled exception. Loaded '/usr/lib/dotnet/shared/Microsoft.NETCore.App/8.0.7/System.Reflection.Metadata.dll'. Symbol loading disabled by Include/Exclude setting.
	
	Exception thrown: 'System.DllNotFoundException' in Uno.UI.Runtime.Skia.Linux.FrameBuffer.dll
	Loaded '/usr/lib/dotnet/shared/Microsoft.NETCore.App/8.0.7/System.Collections.Immutable.dll'. Symbol loading disabled by Include/Exclude setting.
	Exception thrown: 'System.InvalidOperationException' in Uno.UI.Runtime.Skia.Linux.FrameBuffer.dll
	An unhandled exception of type 'System.InvalidOperationException' occurred in Uno.UI.Runtime.Skia.Linux.FrameBuffer.dll: 'Failed to open FrameBuffer device /dev/fb0 (2)'
	Stack trace:
	 >   at Uno.UI.Runtime.Skia.FrameBufferDevice..ctor(String fileName)
	 >   at Uno.UI.Runtime.Skia.Renderer..ctor(IXamlRootHost host)
	 >   at Uno.UI.Runtime.Skia.Linux.FrameBuffer.FrameBufferHost.InnerInitialize()
	 >   at Uno.Helpers.EventLoop.Run() in /__w/1/s/src/Uno.UWP/Helpers/EventLoop.cs:line 152
	Unhandled exception. System.InvalidOperationException: Cannot read keys when either application does not have a console or when console input has been redirected. Try Console.Read.
	   at System.ConsolePal.ReadKey(Boolean intercept)
	   at Uno.UI.Runtime.Skia.Linux.FrameBuffer.FrameBufferHost.<StartConsoleInterception>b__15_0()
	The program 'dotnet' has exited with code 0 (0x0).
	```

____

### Tested with (Upcoming) Uno.Sdk 5.3 Stable
- Microsoft Visual Studio Professional 2022 (64-bit) - Current Version 17.10.4
- Uno.Templates: 5.3.24
- Uno.Sdk: 5.3.24
- Sample app used for the tests: [5.3.24 - UnoTestNavIssue.zip](https://github.com/user-attachments/files/16181119/UnoTestNavIssue.zip)

	#### Results:
	- ✅**Windows**: OK
	- ✅**Android**: OK
	- ✅**WASM**: OK
	- ❌**iOS**: Black screen
	- ❌**Desktop**: Console is launching but not the application
	- ✅**Desktop WSL 2**: OK

**Comment by jeromelaban** [comment]
There's no exception happening, no logging that can indicate what's not working, but there's this in the logs:
```
warn: Uno.Extensions.Storage.FileStorage[0]
      ReadPackageFileAsync - File 'appsettings.keyvaluestorageconfiguration.json' does not exist in package
warn: Uno.Extensions.Storage.FileStorage[0]
      ReadPackageFileAsync - File 'appsettings.appconfig.json' does not exist in package
warn: Uno.Extensions.Storage.FileStorage[0]
      ReadPackageFileAsync - File 'appsettings.localizationconfiguration.json' does not exist in package
warn: Uno.Extensions.Storage.FileStorage[0]
      ReadPackageFileAsync - File 'appsettings.localizationsettings.json' does not exist in package
warn: Uno.Extensions.Storage.FileStorage[0]
      ReadPackageFileAsync - File 'appsettings.navigationconfiguration.json' does not exist in package
warn: Uno.Extensions.Navigation.Navigators.ContentControlNavigator[0]
      Show - Missing view for navigation path ''
```

**Comment by agneszitte** [comment]
> @agneszitte for WSL 2, this is happening because [you have not configured WSLg](https://platform.uno/docs/articles/get-started-vs-2022.html?tabs=ubuntu1804#additional-setup-for-windows-subsystem-for-linux-wsl).

@jeromelaban you are right, I am apparently missing a little bit of setup for Desktop WSL2 on my other machine where I tested the sample for 5.2 stable. I just re-did another test on my other machine that is properly setup and I have an empty window. I have updated the description of the issue for the test with 5.2.
When testing Desktop WS2 with 5.3 stable I don't have any issues anymore.

**Comment by eriklimakc** [comment]
That's an issue with Navigation. If `Toolkit` is added and `UseToolkitNavigation()` is initialized on App.xaml.cs as in

```diff
 var builder = this.CreateBuilder(args)
+     .UseToolkitNavigation()
     .Configure(host => host
....
```

The app will launch and work. Needs further investigation.

**Comment by jeromelaban** [comment]
@dansiegel @nickrandolph This would be a templates issue where the call to `UseToolkitNavigation` should be included.
