### ISSUE TITLE
exception at uno tamplete at wasm release 

### ISSUE THREAD

**Issue by guyulmaz** [unoplatform/uno.extensions#2524]
Hi , I run VS at windows machine , uno latest template solution, I try Release , UnoApp1 (WebAssembly), it is giving error. Debug one is ok. I had selected custom auth and dependency injection features during template wizard. 

## Current behavior

during eun release wasm target it is giving error at browser

fail: Uno.UI.Dispatching.NativeDispatcher[0]
      NativeDispatcher unhandled exception
System.InvalidOperationException: NoConstructorMatch, Uno.Extensions.Authentication.Custom.CustomAuthenticationProvider
   at Microsoft.Extensions.DependencyInjection.ServiceLookup.CallSiteFactory.CreateConstructorCallSite(ResultCache lifetime, ServiceIdentifier serviceIdentifier, Type implementationType, CallSiteChain callSiteChain)
   at Microsoft.Extensi...

## Expected behavior

Brower should show tamplete pages

## How to reproduce it (as minimally and precisely as possible)

I attached the project

## Environment

windows 10 

Nuget Package (s):

Package Version(s):

Affected platform(s):

- [ ] iOS
- [ ] macOS (AppKit)
- [ ] Mac Catalyst
- [ ] Android
- [x ] WebAssembly
- [ ] Windows
- [ ] Skia (WPF)
- [ ] Skia (GTK on Linux/macOS/Windows)
- [ ] Skia (Linux Framebuffer)
- [ ] Build tasks

Visual Studio:

- [ ] 2019 (version: )
- [ x] 2022 (version: )
- [ ] Visual Studio Code (version: )
- [ ] Rider Windows (version: )
- [ ] Rider macOS (version: )

Relevant plugins:

- [ ] Resharper (version: )

## Anything else we need to know?

[UnoApp1.zip](https://github.com/user-attachments/files/16713534/UnoApp1.zip)

**Comment by kazo0** [comment]
Hi @guyulmaz!

Can you try adding the following lines to your LinkerConfig.xml file under the Platforms/WebAssembly folder

```
	<assembly fullname="Uno.Extensions.Authentication">
		<type fullname="Uno.Extensions.Authentication.Custom.CustomAuthenticationProvider" />
	</assembly>
	<assembly fullname="Uno.Extensions.Storage">
		<type fullname="Uno.Extensions.Storage.KeyValueStorage.InMemoryKeyValueStorage" />
	</assembly>
```

**Comment by guyulmaz** [comment]
not changed, still below error is coming at browser

fail: Uno.UI.Dispatching.NativeDispatcher[0]
      NativeDispatcher unhandled exception
System.InvalidOperationException: NoConstructorMatch, Uno.Extensions.Authentication.Custom.CustomAuthenticationProvider
   at Microsoft.Extensions.DependencyInjection.ServiceLookup.CallSiteFactory.CreateConstructorCallSite(ResultCache lifetime, ServiceIdentifier serviceIdentifier, Type implementationType, CallSiteChain callSiteChain)
   at Microsoft.Extensions.DependencyInjection.ServiceLookup.CallSiteFactory.TryCreateExact(ServiceDescriptor descriptor, ServiceIdentifier serviceIdentifier, CallSiteChain callSiteChain, Int32 slot)
   at Microsoft.Extensions.DependencyInjection.ServiceLookup.CallSiteFactory.TryCreateExact(ServiceIdentifier serviceIdentifier, CallSiteChain callSiteChain)
   at Microsoft.Extensions.DependencyInjection.ServiceLookup.CallSiteFactory.CreateCallSite(ServiceIdentifier serviceIdentifier, CallSiteChain callSiteChain)
   at Microsoft.Extensions.DependencyInjection.ServiceLookup.CallSiteFactory.GetCallSite(ServiceIdentifier serviceIdentifier, CallSiteChain callSiteChain)
   at Microsoft.Extensions.DependencyInjection.ServiceProvider.CreateServiceAccessor(ServiceIdentifier serviceIdentifier)
   at System.Collections.Concurrent.ConcurrentDictionary`2[[Microsoft.Extensions.DependencyInjection.ServiceLookup.ServiceIdentifier, Microsoft.Extensions.DependencyInjection, Version=8.0.0.0, Culture=neutral, PublicKeyToken=adb9793829ddae60],[Microsoft.Extensions.DependencyInjection.ServiceProvider.ServiceAccessor, Microsoft.Extensions.DependencyInjection, Version=8.0.0.0, Culture=neutral, PublicKeyToken=adb9793829ddae60]].GetOrAdd(ServiceIdentifier key, Func`2 valueFactory)
   at Microsoft.Extensions.DependencyInjection.ServiceProvider.GetService(ServiceIdentifier serviceIdentifier, ServiceProviderEngineScope serviceProviderEngineScope)
   at Microsoft.Extensions.DependencyInjection.ServiceLookup.ServiceProviderEngineScope.GetService(Type serviceType)
   at Microsoft.Extensions.DependencyInjection.ServiceProviderServiceExtensions.GetRequiredService(IServiceProvider provider, Type serviceType)
   at Microsoft.Extensions.DependencyInjection.ServiceProviderServiceExtensions.GetRequiredService[CustomAuthenticationProvider](IServiceProvider provider)
   at Uno.Extensions.HostBuilderExtensions.<>c__DisplayClass2_0`2[[Uno.Extensions.Authentication.Custom.CustomAuthenticationProvider, Uno.Extensions.Authentication, Version=255.255.255.255, Culture=neutral, PublicKeyToken=null],[Uno.Extensions.Authentication.Custom.CustomAuthenticationSettings, Uno.Extensions.Authentication, Version=255.255.255.255, Culture=neutral, PublicKeyToken=null]].<AddAuthentication>b__1(IServiceProvider sp)
   at Microsoft.Extensions.DependencyInjection.ServiceLookup.CallSiteRuntimeResolver.VisitFactory(FactoryCallSite factoryCallSite, RuntimeResolverContext context)
   at Microsoft.Extensions.DependencyInjection.ServiceLookup.CallSiteVisitor`2[[Microsoft.Extensions.DependencyInjection.ServiceLookup.RuntimeResolverContext, Microsoft.Extensions.DependencyInjection, Version=8.0.0.0, Culture=neutral, PublicKeyToken=adb9793829ddae60],[System.Object, System.Private.CoreLib, Version=8.0.0.0, Culture=neutral, PublicKeyToken=7cec85d7bea7798e]].VisitCallSiteMain(ServiceCallSite callSite, RuntimeResolverContext argument)
   at Microsoft.Extensions.DependencyInjection.ServiceLookup.CallSiteRuntimeResolver.VisitRootCache(ServiceCallSite callSite, RuntimeResolverContext context)
   at Microsoft.Extensions.DependencyInjection.ServiceLookup.CallSiteVisitor`2[[Microsoft.Extensions.DependencyInjection.ServiceLookup.RuntimeResolverContext, Microsoft.Extensions.DependencyInjection, Version=8.0.0.0, Culture=neutral, PublicKeyToken=adb9793829ddae60],[System.Object, System.Private.CoreLib, Version=8.0.0.0, Culture=neutral, PublicKeyToken=7cec85d7bea7798e]].VisitCallSite(ServiceCallSite callSite, RuntimeResolverContext argument)
   at Microsoft.Extensions.DependencyInjection.ServiceLookup.CallSiteRuntimeResolver.VisitIEnumerable(IEnumerableCallSite enumerableCallSite, RuntimeResolverContext context)
   at Microsoft.Extensions.DependencyInjection.ServiceLookup.CallSiteVisitor`2[[Microsoft.Extensions.DependencyInjection.ServiceLookup.RuntimeResolverContext, Microsoft.Extensions.DependencyInjection, Version=8.0.0.0, Culture=neutral, PublicKeyToken=adb9793829ddae60],[System.Object, System.Private.CoreLib, Version=8.0.0.0, Culture=neutral, PublicKeyToken=7cec85d7bea7798e]].VisitCallSiteMain(ServiceCallSite callSite, RuntimeResolverContext argument)
   at Microsoft.Extensions.DependencyInjection.ServiceLookup.CallSiteRuntimeResolver.VisitRootCache(ServiceCallSite callSite, RuntimeResolverContext context)
   at Microsoft.Extensions.DependencyInjection.ServiceLookup.CallSiteVisitor`2[[Microsoft.Extensions.DependencyInjection.ServiceLookup.RuntimeResolverContext, Microsoft.Extensions.DependencyInjection, Version=8.0.0.0, Culture=neutral, PublicKeyToken=adb9793829ddae60],[System.Object, System.Private.CoreLib, Version=8.0.0.0, Culture=neutral, PublicKeyToken=7cec85d7bea7798e]].VisitCallSite(ServiceCallSite callSite, RuntimeResolverContext argument)
   at Microsoft.Extensions.DependencyInjection.ServiceLookup.CallSiteRuntimeResolver.VisitConstructor(ConstructorCallSite constructorCallSite, RuntimeResolverContext context)
   at Microsoft.Extensions.DependencyInjection.ServiceLookup.CallSiteVisitor`2[[Microsoft.Extensions.DependencyInjection.ServiceLookup.RuntimeResolverContext, Microsoft.Extensions.DependencyInjection, Version=8.0.0.0, Culture=neutral, PublicKeyToken=adb9793829ddae60],[System.Object, System.Private.CoreLib, Version=8.0.0.0, Culture=neutral, PublicKeyToken=7cec85d7bea7798e]].VisitCallSiteMain(ServiceCallSite callSite, RuntimeResolverContext argument)
   at Microsoft.Extensions.DependencyInjection.ServiceLookup.CallSiteRuntimeResolver.VisitRootCache(ServiceCallSite callSite, RuntimeResolverContext context)
   at Microsoft.Extensions.DependencyInjection.ServiceLookup.CallSiteVisitor`2[[Microsoft.Extensions.DependencyInjection.ServiceLookup.RuntimeResolverContext, Microsoft.Extensions.DependencyInjection, Version=8.0.0.0, Culture=neutral, PublicKeyToken=adb9793829ddae60],[System.Object, System.Private.CoreLib, Version=8.0.0.0, Culture=neutral, PublicKeyToken=7cec85d7bea7798e]].VisitCallSite(ServiceCallSite callSite, RuntimeResolverContext argument)
   at Microsoft.Extensions.DependencyInjection.ServiceLookup.CallSiteRuntimeResolver.VisitConstructor(ConstructorCallSite constructorCallSite, RuntimeResolverContext context)
   at Microsoft.Extensions.DependencyInjection.ServiceLookup.CallSiteVisitor`2[[Microsoft.Extensions.DependencyInjection.ServiceLookup.RuntimeResolverContext, Microsoft.Extensions.DependencyInjection, Version=8.0.0.0, Culture=neutral, PublicKeyToken=adb9793829ddae60],[System.Object, System.Private.CoreLib, Version=8.0.0.0, Culture=neutral, PublicKeyToken=7cec85d7bea7798e]].VisitCallSiteMain(ServiceCallSite callSite, RuntimeResolverContext argument)
   at Microsoft.Extensions.DependencyInjection.ServiceLookup.CallSiteRuntimeResolver.VisitDisposeCache(ServiceCallSite transientCallSite, RuntimeResolverContext context)
   at Microsoft.Extensions.DependencyInjection.ServiceLookup.CallSiteVisitor`2[[Microsoft.Extensions.DependencyInjection.ServiceLookup.RuntimeResolverContext, Microsoft.Extensions.DependencyInjection, Version=8.0.0.0, Culture=neutral, PublicKeyToken=adb9793829ddae60],[System.Object, System.Private.CoreLib, Version=8.0.0.0, Culture=neutral, PublicKeyToken=7cec85d7bea7798e]].VisitCallSite(ServiceCallSite callSite, RuntimeResolverContext argument)
   at Microsoft.Extensions.DependencyInjection.ServiceLookup.CallSiteRuntimeResolver.Resolve(ServiceCallSite callSite, ServiceProviderEngineScope scope)
   at Microsoft.Extensions.DependencyInjection.ServiceLookup.RuntimeServiceProviderEngine.<>c__DisplayClass4_0.<RealizeService>b__0(ServiceProviderEngineScope scope)
   at Microsoft.Extensions.DependencyInjection.ServiceProvider.GetService(ServiceIdentifier serviceIdentifier, ServiceProviderEngineScope serviceProviderEngineScope)
   at Microsoft.Extensions.DependencyInjection.ServiceLookup.ServiceProviderEngineScope.GetService(Type serviceType)
   at Uno.Extensions.Navigation.Navigators.ControlNavigator.<>c__DisplayClass8_0.<<CreateViewModel>b__0>d.MoveNext()
--- End of stack trace from previous location ---
   at Uno.Extensions.Navigation.Navigators.ControlNavigator.CreateViewModel(IServiceProvider services, NavigationRequest request, Route route, RouteInfo mapping)
   at Uno.Extensions.Navigation.Navigators.ControlNavigator`1.<InitializeCurrentView>d__9[[Microsoft.UI.Xaml.Controls.ContentControl, Uno.UI, Version=255.255.255.255, Culture=neutral, PublicKeyToken=null]].MoveNext()
   at Uno.Extensions.Navigation.Navigators.ControlNavigator`1.<ExecuteRequestAsync>d__8[[Microsoft.UI.Xaml.Controls.ContentControl, Uno.UI, Version=255.255.255.255, Culture=neutral, PublicKeyToken=null]].MoveNext()
   at Uno.Extensions.Navigation.Navigators.ControlNavigator.ControlNavigateAsync(NavigationRequest request)
   at Uno.Extensions.Navigation.Navigators.ControlNavigator.<>c__DisplayClass4_0.<<ControlCoreNavigateAsync>b__0>d.MoveNext()
--- End of stack trace from previous location ---
   at Uno.Extensions.DispatcherExtensions.<>c__DisplayClass2_0`1.<<ExecuteAsync>b__0>d[[Uno.Extensions.Navigation.NavigationResponse, Uno.Extensions.Navigation, Version=255.255.255.255, Culture=neutral, PublicKeyToken=null]].MoveNext()
--- End of stack trace from previous location ---
   at Uno.Extensions.DispatcherQueueExtensions.<>c__DisplayClass0_0`1.<<ExecuteAsync>b__0>d[[Uno.Extensions.Navigation.NavigationResponse, Uno.Extensions.Navigation, Version=255.255.255.255, Culture=neutral, PublicKeyToken=null]].MoveNext()
--- End of stack trace from previous location ---
   at Uno.Extensions.DispatcherQueueExtensions.<ExecuteAsync>d__0`1[[Uno.Extensions.Navigation.NavigationResponse, Uno.Extensions.Navigation, Version=255.255.255.255, Culture=neutral, PublicKeyToken=null]].MoveNext()
   at Uno.Extensions.Dispatcher.<ExecuteAsync>d__4`1[[Uno.Extensions.Navigation.NavigationResponse, Uno.Extensions.Navigation, Version=255.255.255.255, Culture=neutral, PublicKeyToken=null]].MoveNext()
   at Uno.Extensions.Navigation.Navigators.ControlNavigator.ControlCoreNavigateAsync(NavigationRequest request)
   at Uno.Extensions.Navigation.Navigators.ControlNavigator.CoreNavigateAsync(NavigationRequest request)
   at Uno.Extensions.Navigation.Navigator.RegionNavigateAsync(NavigationRequest request)
   at Uno.Extensions.Navigation.Navigator.NavigateAsync(NavigationRequest request)
   at Uno.Extensions.Navigation.FrameworkElementExtensions.<>c__DisplayClass1_1.<<HostAsync>b__6>d.MoveNext()
--- End of stack trace from previous location ---
   at Uno.Extensions.Navigation.FrameworkElementExtensions.Startup(IServiceProvider services, Func`1 afterStartup)
   at Uno.Extensions.ServiceProviderExtensions.BuildAndInitializeHostAsync(Window window, FrameworkElement viewHost, Func`1 buildHost, String initialRoute, Type initialView, Type initialViewModel, Func`3 initialNavigate)
   at Uno.Extensions.ApplicationBuilderExtensions.<NavigateAsync>d__0`1[[UnoApp1.Presentation.Shell, UnoApp1, Version=1.0.0.0, Culture=neutral, PublicKeyToken=null]].MoveNext()
   at UnoApp1.App.OnLaunched(LaunchActivatedEventArgs args)
   at System.Threading.Tasks.Task.<>c.<ThrowAsync>b__128_0(Object state)
   at Uno.UI.Dispatching.NativeDispatcherSynchronizationContext.<>c__DisplayClass3_0.<Post>b__0()
   at Uno.UI.Dispatching.NativeDispatcher.DispatchItems()

**Comment by guyulmaz** [comment]
I also added below ones , but not helped either

  <assembly fullname="Uno.Extensions.Authentication">
    <type fullname="Uno.Extensions.Authentication.Custom.CustomAuthenticationProvider" />
  </assembly>
  <assembly fullname="Uno.Extensions.Storage">
    <type fullname="Uno.Extensions.Storage.KeyValueStorage.InMemoryKeyValueStorage" />
  </assembly>
  <assembly fullname="Microsoft.Extensions.DependencyInjection">
    <type fullname="Microsoft.Extensions.DependencyInjection.ServiceLookup.ServiceIdentifier" />
  </assembly>
    <assembly fullname="Microsoft.Extensions.DependencyInjection">
    <type fullname="Microsoft.Extensions.DependencyInjection.ServiceLookup.RuntimeResolverContext" />
  </assembly>
    <assembly fullname="Uno.Extensions.Navigation">
    <type fullname="Uno.Extensions.Navigation.NavigationResponse" />
  </assembly>
      <assembly fullname="Uno.UI">
    <type fullname="Microsoft.UI.Xaml.Controls.ContentControl" />
  </assembly>

**Comment by guyulmaz** [comment]
Thank you very much after I put them to LinkerConfig.xml file under the Platforms/WebAssembly folder, it run without problem.

But is this a work around, I mean will you somehow optimize it so excluding these assemblies would not be needed at future?

**Comment by jeromelaban** [comment]
@wagenheimer what you're seeing is unrelated to this error, make sure to follow [this doc about IL Trimming](https://platform.uno/docs/articles/common-issues-all-ides.html#runtime-error-no-parameterless-constructor-defined-for-xxxx).
